version: '3.8'

services:
  datalayer_fetcher:
    container_name: datalayer_fetcher
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      selenium-standalone-chromium:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MODULE_NAME=src.main:app
    networks:
      - datalayer_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  selenium-standalone-chromium:
    container_name: selenium-standalone-chromium
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    networks:
      - datalayer_network
    shm_size: '2g'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: "redis:latest"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data 
    networks:
      - datalayer_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis_data:

networks:
  datalayer_network:
