services:
  - type: web
    name: fastapi-example_api
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: seleniarm/standalone-chromium_server
    env: docker
    dockerfilePath: ./Dockerfile.selenium